wri_project_root <- Sys.getenv("WRI_PROJECT_ROOT", unset = "/home/shares/wwri-wildfire")

# This script contains functions for the species domain: 
# valid_check(): Ensures and makes all shapefiles valid, and records if any still cannot be made valid so that they can be fixed manually
# prepare_iucn(): Fixes column names for IUCN data
# prepare_birdlife(): Combines all potentially relevant BirdLife info and AVONET traits info and fixes multisurface geometries so they are usable
# process_species_for_status_or_resilience(): Processes species data for either status or resilience in parallel, including transforming, intersecting with the study area, and checking validity of geometries
# get_spp_info(): Gets species information from the IUCN Red List API for species in our study area, including their threat status and other relevant info


#### Read in some packages needed throughout this script ####
library(terra) # For raster manipulation
library(sf) # For spatial data manipulation
library(tidyverse) # For data manipulation
library(gdalUtilities) # For fixing multisurface geometries


#### Function for shape validity checking ####
# Referenced for valid_check and other code inspiration: https://github.com/mapping-marine-spp-vuln/bc_spp_chi/blob/main/1_setup/species/2_rasterize_iucn_spp_shps.Rmd; https://github.com/mapping-marine-spp-vuln/bc_spp_chi/blob/main/1_setup/species/rasterize_fxns.R
# If this function is run multiple times/for multiple purposes writing to the same folder, you may want to delete the prior files generated by it, as species get appended to the tables generated.
# Ideally, all species are made valid or buffer valid. If they are not valid at the end, you may have to handle separately (ie. by manually fixing the shape).
valid_check <- function(spp_df, output_path) {
  valid <- st_is_valid(spp_df) # Can return a vector if multiple polygons with same ID; this should be ok
  
  id <- unique(spp_df$id_no) # Get the id number of the species
  
  if(all(valid)) {
    message("All valid in ", id) 
    return(spp_df) # If shapes are already valid, return the df
    } else {
    message("Trying to fix ", id, " using st_make_valid()")
    spp_df1 <- st_make_valid(spp_df) # If not, first step is to try st_make_valid()
    
    if(all(st_is_valid(spp_df1))) {
      message("Fixed invalid geoms in ", id, " using st_make_valid()")
      write.table(id, file.path(output_path, "made_valid_ids.csv"), append = TRUE, row.names = FALSE, col.names = "id_no") # Add the id to a table so we know what fixed it if need to do more troubleshooting
      return(spp_df1) # If this works, return the df
      } else {
        # Try zero-distance buffer method
        message("st_make_valid() did not work, trying to fix ", id, " using zero-distance buffer instead")
        spp_df2 <- st_buffer(spp_df1, dist = 0) %>%
          st_cast("MULTIPOLYGON")
        
        if(all(st_is_valid(spp_df2))) {
          
          # Check area before and after buffering to make sure no loss
          area_pre  <- st_area(spp_df) %>% as.numeric() / 1e6
          area_post <- st_area(spp_df2) %>% as.numeric() / 1e6
          
          area_check <- all.equal(area_pre, area_post)
          area_ratio <- max(sum(area_pre) / sum(area_post),
                            sum(area_post) / sum(area_pre))
          
          # Make sure the buffer didn't lose polygons
          if(area_check == FALSE |
             (class(area_check) != 'logical' & area_ratio > 1.001)) {
            # Use all.equal() for near equality, and for comparing all
            # elements in case of a vector. If a difference, choose an arbitrary
            # threshold for "close enough".
            message('Error: ', id, ': area_pre = ', round(sum(area_pre), 3),
                    '; area_post = ', round(sum(area_post), 3),
                    '; area_ratio = ', round(area_ratio, 5), '; not equal!')
            message("Found invalid geometries in ", id, ", adding to a list to check out and make sure it does not remain invalid at end")
            write.table(id, file.path(output_path, "area_not_valid_ids.csv"), append = TRUE, row.names = FALSE, col.names = "id_no") # Write out any area not valid ids to deal with later, but don't stop entire process for it
            return(spp_df1) # Return the shape even if still not valid
          } else {
            message("Fixed invalid geoms in ", id, " using zero-distance buffer!")
            write.table(id, file.path(output_path, "buffer_valid_ids.csv"), append = TRUE, row.names = FALSE, col.names = "id_no") # Add the id to a table so we know what fixed it if need to do more troubleshooting
            return(spp_df2) # Return now valid shape after buffering
          }
        } else {
          message("Found invalid geometries in ", id, ", adding to a list to check out and make sure it does not remain invalid at end")
          write.table(id, file.path(output_path, "not_valid_ids.csv"), append = TRUE, row.names = FALSE, col.names = "id_no") # Write out any not valid ids to deal with later, but don't stop entire process for it
          return(spp_df1) # Return the shape even if still not valid
        }
      }
    }
  }


#### Function for initial preparing of IUCN data ####
prepare_iucn <- function(shps) {
  
  # Change common name inconsistencies so names match across dfs
  for (i in seq_along(shps)) {
    names(shps[[i]]) <- gsub("SHAPE_Leng", "Shape_Leng", names(shps[[i]]))
    names(shps[[i]]) <- gsub("SHAPE_Area", "Shape_Area", names(shps[[i]]))
    names(shps[[i]]) <- gsub("terrestial", "terrestria", names(shps[[i]]))
    # To check how names look now if needed
    # cat("Shapefile", i, "column names:", "\n")
    # print(names(shps[[i]])) 
  }
  
  # Create a reference column order for consistency between dfs
  ref_col_order <- c(
    "id_no", "sci_name", "presence", "origin", "seasonal",
    "compiler", "yrcompiled", "citation", "subspecies", "subpop",
    "source", "island", "tax_comm", "dist_comm", "generalisd",
    "legend", "kingdom", "phylum", "class", "order_",
    "family", "genus", "category", "marine", "terrestria",
    "freshwater", "Shape_Leng", "Shape_Area", "geometry"
  )
  
  # Reorder columns of each object to match the order
  shps <- lapply(shps, function(x) {
    x <- dplyr::select(x, all_of(ref_col_order))
  })
  
  # Return fixed shapes
  return(shps)
}

#### Function for initial preparing of BirdLife data ####
prepare_birdlife <- function(bird_spp, bird_spp_checklist, avonet_traits, output_path) {
  
  # Clean BirdLife checklist column names to be cleaner/more useful later on
  bird_spp_checklist_clean_names <- bird_spp_checklist %>%
    dplyr::rename(sci_name = ScientificName,
                  sisid = SISRecID,
                  order_ = Order_,
                  family = FamilyName,
                  family_alt = Family,
                  category = IUCN_RedList_Category_2024
    ) # Could also use janitor::clean_names(), but I had some specific edits to make so manually changed some names
  
  # Join BirdLife species with the checklist information
  bird_spp_no_traits <- left_join(bird_spp, bird_spp_checklist_clean_names, by = c("sisid", "sci_name"))
  
  # Then add in trait information to that df
  bird_spp_full <- left_join(bird_spp_no_traits, avonet_traits, by = c("sci_name"))
  
  # Fix the column names to be more useful
  bird_spp_full_renamed <- bird_spp_full %>%
    rename(#Shape_Leng = Shape_Length,
           id_no = sisid)
  
  # Cannot change geometry column name piped in above code; need to do the below
  st_geometry(bird_spp_full_renamed) <- "geometry"
  # If I move the renaming, I get this after running the below line of code:
  # Error in UseMethod("st_geometry") : 
  #   no applicable method for 'st_geometry' applied to an object of class "NULL"
  
  # Check for multisurface geometries and fix them, as they are issues later
  multisurface_birds <- bird_spp_full_renamed[st_geometry_type(bird_spp_full_renamed$geometry) == "MULTISURFACE", ]
  non_multisurface_birds <- bird_spp_full_renamed[st_geometry_type(bird_spp_full_renamed$geometry) != "MULTISURFACE", ]
  
  # Write out the multisurface birds to a file to fix them
  st_write(multisurface_birds, file.path(output_path, "multisurface_birds.gpkg"), append = FALSE)
  
  # Use ogr2ogr to fix the multisurface geometries
  ogr2ogr(file.path(output_path, "multisurface_birds.gpkg"), file.path(output_path, "multisurface_birds_fixed.gpkg"), nlt = "MULTIPOLYGON", overwrite = TRUE)
  
  # Read in the fixed multisurface birds
  multisurface_birds_fixed <- st_read(file.path(output_path, "multisurface_birds_fixed.gpkg"))
  
  # Fix the geometry column name again
  st_geometry(multisurface_birds_fixed) <- "geometry"
  
  # Combine the non-multisurface and fixed multisurface birds back together
  bird_spp_fixed <- rbind(non_multisurface_birds, multisurface_birds_fixed)
  
  # Return the fixed bird species data
  return(bird_spp_fixed)
}


#### Function for parallel processing of species for status or resilience ####
process_species_for_status_or_resilience <- function(iucn_shps_filtered, version = "status") {
  # Read in packages needed for function
  library(foreach)
  library(doParallel)
  library(sf)
  library(terra)
  library(dplyr)
  library(tictoc)
  
  # Set up parallelization
  num_cores <- 40
  cl <- makeCluster(num_cores)
  registerDoParallel(cl)
  
  # If it is a list of dfs, get the indices of the list; otherwise, set to 1 if a singular df
  if (!inherits(iucn_shps_filtered, "sf")) {
    indices <- seq_along(iucn_shps_filtered)
  } else if (inherits(iucn_shps_filtered, "sf")) {
    indices <- 1
  }
  
  # Loop over each df in the list or the single sf object
  for (df_index in indices) {
    # Index the list to get a single df if needed or just take the single sf object
    df <- if (length(indices) == 1) iucn_shps_filtered else iucn_shps_filtered[[df_index]]
    
    # Print what df you are on to measure progress
    message("Starting dataframe ", df_index)
    tic() # Start timing of each dataframe for reference
    
    # Get list of unique species ids in the df
    unq_spp_ids <- unique(df$id_no)
    
    # Parallelize across species
    foreach(id = unq_spp_ids, .packages = c("sf", "terra", "dplyr", "here")) %dopar% {
      
      # Ensure s2 is not used for sf operations consistently. If it's on, some may not work as expected.
      sf::sf_use_s2(FALSE)
      
      # Load custom functions within each worker
      source(here("biodiversity", "00_biodiversity_custom_functions.R"))
      
      # Set base paths
      multi_domain_data_path <- file.path(wri_project_root, "data", "multi_domain_data")
      data_file_path <- file.path(wri_project_root, "data", "biodiversity")
      path_year <- "2024" # Set the year for the data file path
      int_data_file_path <- file.path(data_file_path, "int", path_year)
      
      # If the version is resilience or status, set the output path and study area vector accordingly. Include a raster study area for status since we rasterize in status.
      if (version == "resilience") {
        output_path <- file.path(int_data_file_path, "species_dfs_resilience")
        study_area_vect <- st_read(file.path(multi_domain_data_path, "int", "boundary_layers", "admin_boundary_layers", "species_range_north_america_study_area.shp"))
      } else if (version == "status") {
        output_path <- file.path(int_data_file_path, "species_dfs_status")
        study_area_1km <- rast(file.path(output_path, "study_area_1km_biodiversity_status_mask.tif"))
        study_area_vect <- st_read(file.path(multi_domain_data_path, "int", "boundary_layers", "admin_boundary_layers", "wwri_study_area_admin_0_moll.shp"))
      }
      
      # Filter the dataframe to only include the current species id
      spp_df <- df %>%
        filter(id_no == id)
      
      # Try to transform then intersect then run the shape validity check. If that fails, run the valid check first, then transform, check it's still valid, then intersect.
      spp_df_processed <- tryCatch({
        spp_df %>% # spp_df_processed <- 
          st_transform(crs(study_area_vect)) %>%
          st_intersection(study_area_vect) %>%
          valid_check(., output_path = output_path)
      }, error = function(err) {
        spp_df %>% # spp_df_processed <- 
          valid_check(., output_path = output_path) %>%
          st_transform(crs(study_area_vect)) %>%
          valid_check(., output_path = output_path) %>%
          st_intersection(study_area_vect)
      })
      # If the intersected species dataframe is empty, return NULL to skip further processing
      if (nrow(spp_df_processed) == 0) return(NULL)
      
      # If FID column exists/was created, remove it because it is not needed
      if ("FID" %in% names(spp_df_processed)) {
        message("Removing FID column from ", id)
        spp_df_processed <- spp_df_processed %>%
          dplyr::select(-FID)
      }
      
      # The following text files are just to provide information if needed. If a species has multiple categories, origins, or presence values, it will be written out to corresponding files. Nothing specifically is currently done with this information. If running this function multiple times in the same output folder, it will continue to append to old files, so if you need to generate new ones, delete them in advance.
      
      # If multiple threat categories for a species, note in file
      if (length(unique(spp_df_processed$category)) > 1) {
        writeLines(as.character(id), file.path(output_path, paste0(id, "_varied_category.txt")))
      }
      # If multiple origins for a species, note in file
      if (length(unique(spp_df_processed$origin)) > 1) {
        writeLines(as.character(id), file.path(output_path, paste0(id, "_varied_origin.txt")))
      }
      # If multiple presence values for a species, note in file
      if (length(unique(spp_df_processed$presence)) > 1) {
        writeLines(as.character(id), file.path(output_path, paste0(id, "_varied_presence.txt")))
      }
      
      # Final check if any geometries are invalid (they ideally would not be at this point since they already went through a check, but just to be sure)
      if (any(!st_is_valid(spp_df_processed))) {
        # Attempt to fix the invalid geometries one last time
        spp_df_processed_fixed <- st_make_valid(spp_df_processed)
        
        # Check again if any geometries are still invalid after the fix
        if (any(!st_is_valid(spp_df_processed_fixed))) {
          # Log the species ID if fixing did not resolve all invalid geometries
          writeLines(as.character(id), file.path(output_path, paste0(id, "_still_invalid.txt")))
        }
        
        # Use the fixed version only if the original was invalid
        spp_df_processed <- spp_df_processed_fixed
      }
      
      # For resilience, write out the species range intersected with North America
      if (version == "resilience") {
        out_gpkg <- file.path(output_path, paste0(id, "_intersected_resilience.gpkg"))
        st_write(spp_df_processed, out_gpkg, delete_layer = TRUE, quiet = TRUE)
        # For status, reasterize the species to the 1km study area and write out the raster and the intersected species range
      } else if (version == "status") {
        # Rasterize the species range
        spp_rast <- terra::rasterize(spp_df_processed,
                                     study_area_1km,
                                     field = "presence",
                                     fun = "min",
                                     touches = TRUE)
        
        # Convert to a dataframe to store as a csv so that it's easier to work with and takes up less room
        spp_rast_df <- as.data.frame(spp_rast, cells = TRUE)
        
        # Write out the csv
        # Be sure the csv is not blank. This could mean the species range was too small to be rasterized and it may need a buffer or other fix.
        write.csv(spp_rast_df, file.path(output_path, paste0(id, "_raster.csv")), row.names = FALSE)
        
        # Write out intersected raster in case it needs to be inspected
        # Ensure the intersected range is not empty
        st_write(spp_df_processed,
                 file.path(output_path, paste0(id, "_intersected_status.gpkg")),
                 delete_layer = TRUE,
                 quiet = TRUE)
        
        # Write out full range in case it needs to be inspected
        st_write(spp_df,
                 file.path(output_path, paste0(id, "_full_range_status.gpkg")),
                 delete_layer = TRUE,
                 quiet = TRUE)
      }
    }
    toc() # End timing for the current dataframe
  }
  stopCluster(cl) # Stop parallel cluster once done with parallelizing
}


#### Function to get species info from IUCN Red List API ####
get_spp_info <- function(sis_id, key) {
  Sys.sleep(0.5)  # Build in a pause to avoid hitting API rate limits
  
  # Try to fetch species information using the SIS ID and API key
  # If an error occurs, return NULL
  spp_info <- tryCatch(
    rl_sis(id = sis_id, key = key),
    error = function(e) NULL
  )
  
  # If the API call failed and returned NULL, display warning and exit the function early
  if (is.null(spp_info)) {
    warning(paste("Failed for ID:", sis_id))
    return(NULL)
  }
  
  # If successful, extract the taxonomic information list from the API response
  taxon_list <- spp_info$taxon
  
  # Build a tibble with taxonomic fields of interest, using `%||%` to replace NULLs with NA
  taxon_info <- tibble(
    kingdom_name = taxon_list$kingdom_name %||% NA_character_,
    phylum_name = taxon_list$phylum_name %||% NA_character_,
    class_name = taxon_list$class_name %||% NA_character_,
    order_name = taxon_list$order_name %||% NA_character_,
    family_name = taxon_list$family_name %||% NA_character_,
    genus_name = taxon_list$genus_name %||% NA_character_,
    species_name = taxon_list$species_name %||% NA_character_,
    subpopulation_name = taxon_list$subpopulation_name %||% NA_character_,
    authority = taxon_list$authority %||% NA_character_
  ) %>%
    # Create a scientific name field by pasting genus and species names together
    mutate(sciname = paste(genus_name, species_name))
  
  # Extract the assessments data frame from the API response
  assessments <- spp_info$assessments
  
  # Initialize a logical column that will indicate whether each assessment has a global scope
  assessments$has_global_scope <- logical(nrow(assessments))
  
  # Loop over each assessment row to fill this column with Global scope or not (TRUE/FALSE)
  for (i in seq_len(nrow(assessments))) {
    scope_df <- assessments$scopes[[i]]
    
    # Check if the scope information exists and contains a description in English
    if (is.data.frame(scope_df) && "description" %in% names(scope_df)) {
      desc_en <- scope_df$description$en
      # Set `has_global_scope` to TRUE if any scope description is "Global".
      assessments$has_global_scope[i] <- any(desc_en == "Global")
    } else {
      assessments$has_global_scope[i] <- FALSE # If no Global, indicate FALSE
    }
  }
  
  # Filter the assessments:
  # - Keep only the latest entries (could be more than one)
  # - Remove entries with "NA" as a category code (we need a valid status)
  # - Keep only those with global scope (most relevant to us)
  latest_assessment <- assessments %>%
    filter(latest == TRUE & !(red_list_category_code == "NA") & has_global_scope == TRUE) %>%
    slice_max(year_published, n = 1, with_ties = FALSE) # Take the most recent assessment only
  
  # If no latest assessment is found, return NULL and issue a warning
  if (nrow(latest_assessment) == 0) {
    warning(paste("No latest assessment for ID:", sis_id))
    return(NULL)
  }
  
  # Combine the taxonomic information with the latest assessment data
  combined <- cbind(taxon_info, latest_assessment)
  
  # Add the ID column with our naming scheme for reference
  combined$iucn_sid <- sis_id
  
  # Return the final combined df
  return(combined)
}