wri_project_root <- Sys.getenv("WRI_PROJECT_ROOT", unset = "/home/shares/wwri-wildfire")

#### Goal ####
# the goal of the script is to join the two recovery tree traits data pieces into one indicator layer.
# This assumes that the rescaled tifs have been been generated by running the 
# recovery tree traits scripts in the scanfi and treemap folders. The output of this script 
# will be the masked and unmasked final recovery tree traits raster layer.

# This takes about 30 minutes to run on aurora

#### Packages ####
library(tidyverse)
library(data.table)
library(terra)

#### Setup and File Paths ####
year_of_interest <- 2024
natural_habitats_base_path <- file.path(wri_project_root, "data", "natural_habitats")
multi_domain_data_file_path <- file.path(wri_project_root, "data", "multi_domain_data")

# tree_traits rasters
treemap_tree_traits_recovery_path <- file.path(natural_habitats_base_path, "int/treemap/treemap_tree_traits_recovery_90m.tif")
scanfi_tree_traits_recovery_path <- file.path(natural_habitats_base_path, "int/scanfi/scanfi_tree_traits_recovery_90m.tif")

# Template raster path for alignment function
template_raster_path <- file.path(multi_domain_data_file_path, 
                                  "int/boundary_layers/admin_boundary_layers/wwri_study_area_raster_mask_lvl_0_90m_with_na.tif")
template_raster <- rast(template_raster_path)

source(here::here("templates_and_functions", "align_raster_to_template.R"))

# ag/urban mask
ag_urban_mask_path <- paste0(natural_habitats_base_path, "int/esri_present_landcover/", year_of_interest, "/full_masks/full_ag_urban_mask_90m_5070.tif")

# if the ag_urban mask file does not exist use the previous years data
if (!file.exists(ag_urban_mask_path)) {
  ag_urban_mask_path <- paste0(natural_habitats_base_path, "int/esri_present_landcover/", year_of_interest - 1, "/full_masks/full_ag_urban_mask_90m_5070.tif")
}

# Save paths
rescaled_save_path <- paste0(natural_habitats_base_path, "rescaled_indicators/", year_of_interest, "/")

final_layer_root <- file.path(wri_project_root, "final_layers")
final_layer_save_path_no_mask <- paste0(final_layer_root, year_of_interest, "/natural_habitats/indicators_no_mask/")
final_layer_save_path_mask <- paste0(final_layer_root, year_of_interest, "/natural_habitats/indicators_mask/")

#### Main Processing ####
# read in the trait rasters
treemap_tree_traits_recovery_raster <- rast(treemap_tree_traits_recovery_path)
scanfi_tree_traits_recovery_raster <- rast(scanfi_tree_traits_recovery_path)

# Conduct data checks to make sure the rasters are the same size, crs, and extent
# If they are not the same, make the status raster to match the template raster
treemap_tree_traits_recovery_raster_aligned <- align_raster_to_template(template_raste = template_raster, 
                                                                      input_raster = treemap_tree_traits_recovery_raster,
                                                                      input_type = "continuous")
scanfi_tree_traits_recovery_raster_aligned <- align_raster_to_template(template_raste = template_raster,
                                                                     input_raster = scanfi_tree_traits_recovery_raster,
                                                                     input_type = "continuous")

# change the layer names to traits_recovery
names(treemap_tree_traits_recovery_raster_aligned) <- "treemap_tree_traits_recovery"
names(scanfi_tree_traits_recovery_raster_aligned) <- "scanfi_tree_traits_recovery"

# mosaic the traits rasters into one layer in one raster
tree_traits_recovery_raster <- terra::mosaic(treemap_tree_traits_recovery_raster_aligned, 
                                           scanfi_tree_traits_recovery_raster_aligned, 
                                           fun = "mean")

# change the layer name to recovery_tree_traits
names(tree_traits_recovery_raster) <- "recovery_tree_traits"

#remove all tree_traits stuff except for the last raster
rm(treemap_tree_traits_recovery_raster, scanfi_tree_traits_recovery_raster,
   treemap_tree_traits_recovery_raster_aligned, scanfi_tree_traits_recovery_raster_aligned)

# save unmaasked version in two places
writeRaster(tree_traits_recovery_raster, 
            filename = file.path(final_layer_save_path_no_mask, "natural_habitats_recovery_tree_traits.tif"), 
            overwrite = TRUE)
writeRaster(tree_traits_recovery_raster,
            filename = file.path(rescaled_save_path, "natural_habitats_recovery_tree_traits.tif"), 
            overwrite = TRUE)

# mask with the ag_urban mask
ag_urban_mask <- rast(ag_urban_mask_path)

# make sure it is aligned for masking
ag_urban_mask_aligned <- align_raster_to_template(template_raster = template_raster, 
                                                  input_raster = ag_urban_mask,
                                                  input_type = "categorical")

# mask the tree_traits recovery raster with the ag_urban mask
tree_traits_recovery_raster_masked <- mask(tree_traits_recovery_raster, ag_urban_mask_aligned, inverse = TRUE)

# run through the alignment function again before saving
tree_traits_recovery_raster_masked <- align_raster_to_template(template_raster = template_raster, 
                                                             input_raster = tree_traits_recovery_raster_masked,
                                                             input_type = "continuous")

# save the masked version in masked final_layer
writeRaster(tree_traits_recovery_raster_masked, 
            filename = file.path(final_layer_save_path_mask, "natural_habitats_recovery_tree_traits.tif"), 
            overwrite = TRUE)
